### ISSUE TITLE
`extract_taxa` replaces non-number trait values with NA

### ISSUE THREAD

**Issue by rubysaltbush** [traitecoevo/austraits#52] opened 2022-09-14 05:15 UTC
Hello!

Someone asked me why their austraits extraction for Veronica lifespan wasn't working, and having investigated it looks like there's a bug in the `extract_taxa` function which they were using which replaces all non-number trait values (e.g. character values like ">50" for lifespan) with NAs.

My script to reproduce this bug is below:

```
#install.packages("tidyverse")
#install.packages("remotes")
remotes::install_github("traitecoevo/austraits", dependencies = TRUE, upgrade = "ask")
library(tidyverse)
library(austraits)

austraits <- austraits::load_austraits(version = "3.0.2")

# filter just to Veronica genus and lifespan trait
#first extract data just for Veronica

veronica <- austraits::extract_taxa(austraits, genus = "Veronica")

# then filter to just the lifespan trait
veronica_lifespan <- veronica$traits %>%
  dplyr::filter(trait_name == "lifespan")

head(veronica_lifespan)

# A tibble: 6 × 12
  dataset_id taxon_n…¹ site_…² conte…³ obser…⁴ trait…⁵ value unit  date  value…⁶ repli…⁷
  <chr>      <chr>     <chr>   <chr>   <chr>   <chr>   <dbl> <chr> <chr> <fct>   <chr>  
1 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp…    NA NA    NA    expert… NA     
2 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp…    NA NA    NA    expert… NA     
3 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp…    NA NA    NA    expert… NA     
4 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp…    NA NA    NA    expert… NA     
5 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp…    NA NA    NA    expert… NA     
6 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp…    NA NA    NA    expert… NA     
# … with 1 more variable: original_name <chr>, and abbreviated variable names
#   ¹​taxon_name, ²​site_name, ³​context_name, ⁴​observation_id, ⁵​trait_name, ⁶​value_type,
#   ⁷​replicates
```
As you can see using `extract_taxa` to get this data gives only NAs in the value column. 

When you filter just using standard dplyr filter functions though there are data in the value column:

```
lifespan <- austraits$traits %>%
  dplyr::filter(trait_name == "lifespan")

veronica_lifespan_manual <- lifespan %>%
  dplyr::filter(grepl("Veronica", taxon_name))

head(veronica_lifespan_manual)

# A tibble: 6 × 12
  dataset_id taxon_n…¹ site_…² conte…³ obser…⁴ trait…⁵ value unit  date  value…⁶ repli…⁷
  <chr>      <chr>     <chr>   <chr>   <chr>   <chr>   <chr> <chr> <chr> <fct>   <chr>  
1 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp… <100  NA    NA    expert… NA     
2 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp… <100  NA    NA    expert… NA     
3 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp… <100  NA    NA    expert… NA     
4 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp… <100  NA    NA    expert… NA     
5 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp… <100  NA    NA    expert… NA     
6 Cheal_2017 Veronica… NA      NA      Cheal_… lifesp… <100  NA    NA    expert… NA     
# … with 1 more variable: original_name <chr>, and abbreviated variable names
#   ¹​taxon_name, ²​site_name, ³​context_name, ⁴​observation_id, ⁵​trait_name, ⁶​value_type,
#   ⁷​replicates
``` 

Looking at the traits missing values after the `extract_taxa` function they all seem to be non-number (character) values.

```
veronica_extract_NAs <- veronica$traits %>%
  dplyr::filter(is.na(value))

head(unique(veronica_extract_NAs$trait_name))

[1] "fire_and_establishing"     "fire_cued_seeding"         "fire_response"            
[4] "fire_response_juvenile"    "fire_response_on_maturity" "life_history"
```

**Comment by fontikar** [comment] 2022-09-14 05:33
Hey @rubysaltbush 

Thanks for bringing this to my attention and for your deep dive explanation! 

I can confirm that I can reproduce this bug! 🐛 and will take a closer look tomorrow to try fix this issue!

**Comment by fontikar** [comment] 2022-09-14 05:51
Interestingly, the order of `extract_trait` and `extract_taxa` makes a difference

```r
# Extract trait first
austraits |> extract_trait("lifespan") -> lifespan

# Extract taxa after
lifespan |> extract_taxa(genus = "Veronica") -> trait_first

# Actual values
trait_first$traits$value ```

**Comment by fontikar** [comment] 2022-09-29 04:10
Hi @rubysaltbush! 
I found the bug 🐛🔍 - turns out character values were converted to numeric during `extract_trait` and `extract_taxa`! I've now fixed the bug with a more refined conditional statement :) 

I believe the both `extract_trait` and `extract_taxa` works regardless of order! Furthermore, both functions will play well with dplyr::filter and using grep/stringr to detect genus names :) 

```r 
austraits |> extract_taxa(genus = "Veronica") |> extract_trait(trait_names = "lifespan") -> genus_first
genus_first$traits$value
 "<100" "<100" "<100" "<100" "<100" "<100" "<100" "<100" "<50"  "<50"  "<50"  "<50"  "<50" 
"<50"  "<50"  "<50"  "<50"  "<50"  "<50"  "<50"  "<50"  ">500" "<50"  ">500" ">500" ">500"
 ">500" ">500" ">500" ">500" ">500" ">500" ">500" ">500" ">500"

austraits |> extract_trait(trait_names = "lifespan") |> extract_taxa(genus = "Veronic") -> trait_first
 trait_first$traits$value
"<100" "<100" "<100" "<100" "<100" "<100" "<100" "<100" "<50"  "<50"  "<50"  "<50"  "<50" 
 "<50"  "<50"  "<50"  "<50"  "<50"  "<50"  "<50"  "<50"  ">500" "<50"  ">500" ">500" ">500" ">500" ">500" ">500" ">500" ">500" ">500" ">500" ">500" ">500"
 
 austraits |> extract_taxa(genus = "Veronica") -> veronica

veronica$traits |>  
  dplyr::filter(trait_name == "lifespan") |> 
  pull(value)


austraits |> extract_trait(trait_names = "lifespan") -> lifespan

lifespan$traits |>  
  dplyr::filter(stringr::str_detect(taxon_name, "Veronica")) |> 
  pull(value)
 ```

**Closed** 2022-09-29 04:14 UTC
Labels: bug 🐛
